const mongoose = require('mongoose');

const cbsmSchema = new mongoose.Schema({
    studentRegisterNumber:{
        type:String
    },
    studentClass:{
        type:String
    },
    MonthltTest1:[{
        "Kannada":{
            _id:false,
            type:String
        },
        "English":{
            _id:false,
            type:String
        },
        "Hindi":{
            _id:false,
            type:String
        },
        "Mathematics":{
            _id:false,
            type:String
        },
        "Science":{
            _id:false,
            type:String
        },
        "SocialStudies":{
            _id:false,
            type:String
        }
    }],
    MonthltTest2:[{
        "Kannada":{
            _id:false,
            type:String
        },
        "English":{
            _id:false,
            type:String
        },
        "Hindi":{
            _id:false,
            type:String
        },
        "Mathematics":{
            _id:false,
            type:String
        },
        "Science":{
            _id:false,
            type:String
        },
        "SocialStudies":{
            _id:false,
            type:String
        }
    }],
    MonthltTest3:[{
        "Kannada":{
            _id:false,
            type:String
        },
        "English":{
            _id:false,
            type:String
        },
        "Hindi":{
            _id:false,
            type:String
        },
        "Mathematics":{
            _id:false,
            type:String
        },
        "Science":{
            _id:false,
            type:String
        },
        "SocialStudies":{
            _id:false,
            type:String
        }
    }],
    MonthltTest4:[{
        "Kannada":{
            _id:false,
            type:String
        },
        "English":{
            _id:false,
            type:String
        },
        "Hindi":{
            _id:false,
            type:String
        },
        "Mathematics":{
            _id:false,
            type:String
        },
        "Science":{
            _id:false,
            type:String
        },
        "SocialStudies":{
            _id:false,
            type:String
        }
    }],
    MidTerm:[{
        "Kannada":{
            _id:false,
            type:String
        },
        "English":{
            _id:false,
            type:String
        },
        "Hindi":{
            _id:false,
            type:String
        },
        "Mathematics":{
            _id:false,
            type:String
        },
        "Science":{
            _id:false,
            type:String
        },
        "SocialStudies":{
            _id:false,
            type:String
        }
    }],
    FinalTerm:[{
        "Kannada":{
            _id:false,
            type:String
        },
        "English":{
            _id:false,
            type:String
        },
        "Hindi":{
            _id:false,
            type:String
        },
        "Mathematics":{
            _id:false,
            type:String
        },
        "Science":{
            _id:false,
            type:String
        },
        "SocialStudies":{
            _id:false,
            type:String
        }
    }]
});
const cbscmarks = mongoose.model('Cbscstudentmark',cbsmSchema);
module.exports = cbscmarks;