const mongoose = require('mongoose');


const cbscSubjectsMarksSchema = new mongoose.Schema({
    studentRegisterNumber:{
        type:String
    },
    studentClass:{
        type:String
    },
    Kannada:[{
        "monthlyTest1":{
            _id:false,
            type:String
        },
        "monthlyTest2":{
            _id:false,
            type:String
        },
        "midTerm":{
            _id:false,
          type:String
        },
        "monthlyTest3":{
            _id:false,
          type:String
        },
        "monthlyTest4":{
            _id:false,
          type:String
        },
        "finalTerm":{
            _id:false,
          type:String
        },
}],
English:[{
    "monthlyTest1":{
            _id:false,
          type:String
        },
    "monthlyTest2":{
            _id:false,
          type:String
        },
    "midTerm":{
            _id:false,
          type:String
        },
    "monthlyTest3":{
            _id:false,
          type:String
        },
    "monthlyTest4":{
            _id:false,
          type:String
        },
    "finalTerm":{
            _id:false,
          type:String
        },
}],
Hindi:[{
    "monthlyTest1":{
            _id:false,
          type:String
        },
    "monthlyTest2":{
            _id:false,
          type:String
        },
    "midTerm":{
            _id:false,
          type:String
        },
    "monthlyTest3":{
            _id:false,
          type:String
        },
    "monthlyTest4":{
            _id:false,
          type:String
        },
    "finalTerm":{
            _id:false,
          type:String
        },
}],
Mathematics:[{
    "monthlyTest1":{
            _id:false,
          type:String
        },
    "monthlyTest2":{
            _id:false,
          type:String
        },
    "midTerm":{
            _id:false,
          type:String
        },
    "monthlyTest3":{
            _id:false,
          type:String
        },
    "monthlyTest4":{
            _id:false,
          type:String
        },
    "finalTerm":{
            _id:false,
          type:String
        }
}],
Science:[{
    "monthlyTest1":{
            _id:false,
          type:String
        },
            "monthlyTest2":{
            _id:false,
          type:String
        },
            "midTerm":{
            _id:false,
          type:String
        },
            "monthlyTest3":{
            _id:false,
          type:String
        },
            "monthlyTest4":{
            _id:false,
          type:String
        },
            "finalTerm":{
            _id:false,
          type:String
        },
}],
SocialStudies:[{
    "monthlyTest1":{
            _id:false,
          type:String
        },
    "monthlyTest2":{
            _id:false,
          type:String
        },
    "midTerm":{
            _id:false,
          type:String
        },
    "monthlyTest3":{
            _id:false,
          type:String
        },
    "monthlyTest4":{
            _id:false,
          type:String
        },
    "finalTerm":{
            _id:false,
          type:String
        },
}]
});

const cbscSubjectsMarks = mongoose.model('CbscSubjectsMark',cbscSubjectsMarksSchema);
module.exports = cbscSubjectsMarks;